;The Bigger the update value, the slower the image will move and vice versa.
[Rainmeter]
Update=100

[Metadata]
Name=GIFFrames
Author=Rainmeter Team
Information=Displays a deconstructed .gif file (individual frames) as if it was a .gif file.
Version=Jan 16, 2016
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0

[ImageNumberCalc]
Measure=Calc
Formula=Counter % 1

[ImageMeter]
Meter=Image
ImageName=#@#frame_[ImageNumberCalc].png
;If you want to edit the size of the gif, uncomment the next two lines
;W={// ENTER YOUR DESIRED WIDTH}
;H={// ENTER YOUR DESIRED HEIGHT}
AntiAlias=1
DynamicVariables=1
